export default {
  // Not found page
  not_found: {
    title: "Page not found",
    description: "The page you are looking for does not exist.",
    back_to_home: "Back to home",
  },
  // Error page
  error: {
    title: "Something went wrong!",
  },
  // Theme related translations
  theme: {
    toggle_theme: "Toggle theme",
    dark: "Dark",
    light: "Light",
    system: "System",
  },
  // Alert dialog translations
  alert_dialog: {
    delete_element: {
      title: "Are you absolutely sure?",
      description: "This action cannot be undone.",
      pending: "Deleting...",
      success: "Deleted successfully",
      error: "Failed to delete.",
    },
    save_element: {
      pending: "Saving...",
      success: "Saved successfully",
      error: "Failed to save.",
    },
    cancel: "Cancel",
    continue: "Continue",
  },
  // Landing page translations
  landing: {
    hero: {
      title: "ChatTTS: Text-to-Speech Project for Realistic Conversation",
      subtitle:
        "ChatTTS.Site - The Ultimate Guide to Using the Open-Source Text-to-Speech Project for Realistic Conversation Simulation",
      description:
        "Welcome to ChatTTS.Site – Your comprehensive resource for mastering ChatTTS, an innovative Open-Source Text-to-Speech project. Here, you will learn how to harness the power of ChatTTS to generate lifelike, dynamic voice dialogues for realistic conversation simulation. Whether you're a developer seeking to integrate advanced speech technology into your applications, an AI enthusiast, or a user keen on having human-like conversations driven by text inputs, this guide will walk you through every step, from getting started to advanced usage. Discover the future of conversational AI today with ChatTTS.",
      tagline: "Your assistant, now with a voice - Discover ChatTTS.",
      sub_tagline:
        "No more silent chats. Bring life to your conversation with ChatTTS, connect and engage with interactive voice-enabled dialogue using just a click.",
      cta_local: "Using Locally!",
      cta_demo: "Start Free Online!",
      small_note: "Available in English and Chinese",
      badge: "Open Source",
    },

    features: {
      title: "ChatTTS Features",
      description: "Why ChatTTS",
      items: [
        {
          title: "Realistic Text-to-Speech",
          description:
            "Make your audio generated by AI sound like a real person with human-like intonations and pauses.",
        },
        {
          title: "Language Support",
          description:
            "Break the language barrier with our dual language support for English and Chinese.",
        },
        {
          title: "Well-Trained",
          description:
            "Rest assured in the efficiency of ChatTTS, designed from over 40,000 hours of pre training",
        },
        {
          title: "Open-Source",
          description:
            "Get access to well-maintained and regularly updated source code on GitHub.",
        },
      ],
    },

    pricing: {
      title: "Pricing",
      description:
        "Choose the plan that best suits your needs. All plans come with a set of pre-configured features to help you get started quickly.",
      get_started: "Get Started",
      features: "Features",
      coming_soon: "Coming soon!",
      most_popular: "Most Popular",
      starter: {
        title: "Starter",
        price: "Free",
        description:
          "Pre-configured boilerplate code for common features to jump-start your app.",
      },

      pro: {
        title: "Pro",
        description: "For advanced projects that need extra power.",
      },

      all_features: {
        feature_next: "Next.js 14 with app router",
        feature_prisma: "Prisma ORM",
        feature_clerk: "Clerk authentication",
        feature_supabase: "Supabase integration",
        feature_resend: "Resend integration",
        feature_sentry: "Sentry integration",
        feature_i18n: "i18n support",
        feature_tailwind: "Tailwind & shadcn components",
        feature_dashboard: "Dashboard template",
        feature_landing: "Landing page template",
        feature_openai: "OpenAI integration",
        feature_lemon: "Lemon Squeezy integration",
        feature_mdx: "MDX Documentation support",
      },
    },

    how_it_works: {
      title: "How ChatTTS Works",
      description_local:
        "Let's start using this repository locally with basic usage. Convert text into natural conversational human voice.",
      description:
        "Using ChatTTS is easy. Simply input your dialogue, execute a few lines of our code, and listen to your conversation come to life. For developers or new users; our clear and concise documentation guides are available to help every step of the way.",
      note: "To generate a 30-second audio clip, a minimum of 4GB GPU memory is essential. In the case of the 4090 GPU, it has the capacity to produce audio that corresponds to roughly 7 semantic tokens every second. The Real-Time Factor (RTF) is approximately 0.3.",
      steps: {
        s1: {
          id: "1",
          title: "Clone Project from GitHub",
          description:
            "Navigate to the open-source repository, choose the appropriate folder, and clone the remote repository to your local machine using git commands. Alternatively, you can choose to manually download it from GitHub.",
        },
        s2: {
          id: "2",
          title: "Install Reqirements",
          description:
            "Enter the folder where you downloaded the files in the terminal or command line, then run the following command to download the dependencies, which are listed in the requirements.txt file.",
        },
        s3: {
          id: "3",
          title: "Initialize ChatTTS",
          description:
            "Import the package, and declare the Python modules and instances we need.",
        },
        s4: {
          id: "4",
          title: "Declare Your Text",
          description:
            "Determine the text you need to generate speech for, and save it as 'texts'.",
        },
        s5: {
          id: "5",
          title: "Generate Audio",
          description: "Generate the speech.",
        },
        s6: {
          id: "6",
          title: "Save Wav File",
          description: "Save the speech to your local machine.",
        },
      },
    },

    faq: {
      title: "FAQs about ChatTTS",
      description:
        "Frequently Asked Questions for the ChatTTS GitHub repository, a generative speech model for daily dialogue.",
      content: [
        {
          title: "What is ChatTTS?",
          description:
            "ChatTTS is a text-to-speech model designed specifically for dialogue scenarios such as LLM assistants. It supports both English and Chinese languages and is trained with over 100,000 hours composed of Chinese and English. The open-source version on HuggingFace is a 40,000-hour pre-trained model.",
        },
        {
          title: "Is ChatTTS free to use?",
          description:
            "Yes, ChatTTS is free to use. You can download the project files from the GitHub repository to your local machine. There are also other developers who have created free versions available on well-known open-source platforms such as Github, HuggingFace and Modelscope.",
        },
        {
          title: "How do I install ChatTTS?",
          description:
            "Installation steps for ChatTTS are outlined in the 'How it works' section. Basicly, you could directly downlownd the text-to-speech project into your laptop from Github repo and use it in python. You can also follow the prompts on the official GitHub page for downloading and using ChatTTS.",
        },
        {
          title: "Where can I find the source code for ChatTTS?",
          description:
            "The source code for ChatTTS can be found on its GitHub repository at https://github.com/2noise/ChatTTS.",
        },
        {
          title: "In what languages is ChatTTS available?",
          description: "ChatTTS is currently available in English and Chinese.",
        },
        {
          title: "How do I use ChatTTS in my project?",
          description:
            "To use ChatTTS in your project, you can import it and use the `chat.infer` method with your text. More detailed usage examples might be available in the repository's documentation or example files.",
        },
        {
          title: "Can I contribute to the ChatTTS project?",
          description:
            "Yes, contributions to the ChatTTS project are welcome in various forms, including issue discussions, GitHub issues submissions, and pull requests. You can also join the QQ group: 808364215 for discussions.",
        },
        {
          title: "What kind of support does ChatTTS offer?",
          description:
            "For formal inquiries about the model and its roadmap, you can contact the developers at open-source@2noise.com. Joining their QQ group or submitting GitHub issues for support is also encouraged.",
        },
        {
          title: "How is ChatTTS different from other TTS models?",
          description:
            "ChatTTS is optimized for dialogue-based tasks, enabling natural and expressive speech synthesis with support for multiple speakers. It offers fine-grained control over prosodic features like laughter, pauses, and interjections, and surpasses most open-source TTS models in terms of prosody.",
        },
      ],
    },

    waitlist: {
      title: "Get Early Access",
      description:
        "Join our waitlist to get notified when we launch new features. We will never spam you.",
      form: {
        email: "Email Address",
        join_waitlist: "Join Waitlist",
      },
    },

    nav: {
      features: "Features",
      pricing: "Pricing",
      faq: "FAQ",
      docs: "Docs",
      dashboard: "Dashboard",
      sign_in_for_demo: "Sign in for Demo",
    },
  },
} as const;
